---
name: github-action-request-reviews
description: >-
  request pr reviews
branding:
  icon: package
  color: green
inputs:
  pr:
    description: id or pr
  repository:
    description: repository
  teams:
    description: teams to request reviews from
  token:
    description: 'The gitea token or personal access token'
    required: false
    default: ${{ github.token }}
outputs:
  more:
    description: more reviews? 'true' or 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
